//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace memoral.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factore
    {
        public int FactoreId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
        public string Frq_request { get; set; }
    }
}
